"""Curated multi-country registry: a mixture of high-, middle-, and
lower-income governments so the benchmark compares information navigability
across very different public-information ecosystems.

Each entry follows the same shape as the Bangladesh registry. URLs are the
stable, well-known official domains; sources that have moved or gone dark
show up as crawl failures — which the accessibility score is designed to
capture, so imperfect URLs degrade honestly rather than silently.

Institution types: ministry, parliament, audit, statistics, central_bank,
procurement (matching the six pillars the scoring questions probe).
"""
from __future__ import annotations


def _country(
    name: str,
    code: str,
    aliases: list[str],
    domains: list[str],
    description: str,
    institutions: list[tuple[str, str, str]],
    sources: list[tuple[str, str, str, float]],
) -> dict:
    return {
        "government_name": name,
        "country_code": code,
        "jurisdiction_type": "national",
        "aliases": sorted({name.lower(), code.lower(), *[a.lower() for a in aliases]}),
        "official_domains": domains,
        "description": description,
        "institutions": [
            {"name": iname, "institution_type": itype, "website_url": iurl}
            for iname, itype, iurl in institutions
        ],
        "sources": [
            {
                "name": sname,
                "url": surl,
                "source_type": stype,
                "institution": None,
                "reliability_score": reliability,
            }
            for sname, surl, stype, reliability in sources
        ],
    }


COUNTRIES: list[dict] = [
    # ------------------------------------------------------ high-income ----
    _country(
        "Government of the United States",
        "US",
        ["united states", "usa", "america", "united states of america",
         "federal government of the united states", "u.s."],
        ["usa.gov", "whitehouse.gov"],
        "Federal government of the United States of America.",
        [
            ("Department of the Treasury", "ministry", "https://home.treasury.gov"),
            ("U.S. Congress", "parliament", "https://www.congress.gov"),
            ("Government Accountability Office", "audit", "https://www.gao.gov"),
            ("U.S. Census Bureau", "statistics", "https://www.census.gov"),
            ("Federal Reserve", "central_bank", "https://www.federalreserve.gov"),
            ("General Services Administration", "procurement", "https://www.gsa.gov"),
        ],
        [
            ("USAspending — federal spending data", "https://www.usaspending.gov", "budget", 0.9),
            ("Treasury Fiscal Data", "https://fiscaldata.treasury.gov", "budget", 0.9),
            ("SAM.gov — contract opportunities", "https://sam.gov", "procurement", 0.9),
            ("GAO reports", "https://www.gao.gov", "audit", 0.9),
            ("Congress.gov — legislation", "https://www.congress.gov", "parliament", 0.9),
            ("Federal Register", "https://www.federalregister.gov", "legal", 0.9),
            ("Bureau of Labor Statistics", "https://www.bls.gov", "statistics", 0.9),
            ("AP News", "https://apnews.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of the United Kingdom",
        "GB",
        ["united kingdom", "uk", "britain", "great britain", "his majesty's government"],
        ["gov.uk"],
        "Government of the United Kingdom of Great Britain and Northern Ireland.",
        [
            ("HM Treasury", "ministry", "https://www.gov.uk/government/organisations/hm-treasury"),
            ("UK Parliament", "parliament", "https://www.parliament.uk"),
            ("National Audit Office", "audit", "https://www.nao.org.uk"),
            ("Office for National Statistics", "statistics", "https://www.ons.gov.uk"),
            ("Bank of England", "central_bank", "https://www.bankofengland.co.uk"),
            ("Crown Commercial Service", "procurement", "https://www.gov.uk/government/organisations/crown-commercial-service"),
        ],
        [
            ("GOV.UK portal", "https://www.gov.uk", "government", 0.9),
            ("Find a Tender", "https://www.find-tender.service.gov.uk", "procurement", 0.9),
            ("Contracts Finder", "https://www.gov.uk/contracts-finder", "procurement", 0.9),
            ("National Audit Office reports", "https://www.nao.org.uk", "audit", 0.9),
            ("Office for National Statistics", "https://www.ons.gov.uk", "statistics", 0.9),
            ("UK Parliament", "https://www.parliament.uk", "parliament", 0.9),
            ("legislation.gov.uk", "https://www.legislation.gov.uk", "legal", 0.9),
            ("BBC News", "https://www.bbc.co.uk/news", "news", 0.6),
        ],
    ),
    _country(
        "Federal Government of Germany",
        "DE",
        ["germany", "deutschland", "bundesregierung", "federal republic of germany"],
        ["bund.de", "bundesregierung.de"],
        "Federal government of the Federal Republic of Germany.",
        [
            ("Bundesministerium der Finanzen", "ministry", "https://www.bundesfinanzministerium.de"),
            ("Deutscher Bundestag", "parliament", "https://www.bundestag.de"),
            ("Bundesrechnungshof", "audit", "https://www.bundesrechnungshof.de"),
            ("Statistisches Bundesamt", "statistics", "https://www.destatis.de"),
            ("Deutsche Bundesbank", "central_bank", "https://www.bundesbank.de"),
            ("Beschaffungsamt des BMI", "procurement", "https://www.bescha.bund.de"),
        ],
        [
            ("Bundeshaushalt — federal budget data", "https://www.bundeshaushalt.de", "budget", 0.9),
            ("service.bund.de — notices and tenders", "https://www.service.bund.de", "procurement", 0.85),
            ("Bundesrechnungshof reports", "https://www.bundesrechnungshof.de", "audit", 0.9),
            ("Destatis — federal statistics", "https://www.destatis.de", "statistics", 0.9),
            ("Bundestag", "https://www.bundestag.de", "parliament", 0.9),
            ("Gesetze im Internet — federal law", "https://www.gesetze-im-internet.de", "legal", 0.9),
            ("GovData — open data", "https://www.govdata.de", "statistics", 0.85),
            ("tagesschau", "https://www.tagesschau.de", "news", 0.6),
        ],
    ),
    _country(
        "Government of France",
        "FR",
        ["france", "république française", "republique francaise", "french republic"],
        ["gouvernement.fr", "service-public.fr"],
        "Government of the French Republic.",
        [
            ("Ministère de l'Économie et des Finances", "ministry", "https://www.economie.gouv.fr"),
            ("Assemblée nationale", "parliament", "https://www.assemblee-nationale.fr"),
            ("Cour des comptes", "audit", "https://www.ccomptes.fr"),
            ("INSEE", "statistics", "https://www.insee.fr"),
            ("Banque de France", "central_bank", "https://www.banque-france.fr"),
            ("Direction des Achats de l'État", "procurement", "https://www.economie.gouv.fr/dae"),
        ],
        [
            ("budget.gouv.fr — state budget", "https://www.budget.gouv.fr", "budget", 0.9),
            ("BOAMP — public procurement notices", "https://www.boamp.fr", "procurement", 0.9),
            ("Cour des comptes reports", "https://www.ccomptes.fr", "audit", 0.9),
            ("INSEE statistics", "https://www.insee.fr", "statistics", 0.9),
            ("Assemblée nationale", "https://www.assemblee-nationale.fr", "parliament", 0.9),
            ("Légifrance — law and gazette", "https://www.legifrance.gouv.fr", "legal", 0.9),
            ("data.gouv.fr — open data", "https://www.data.gouv.fr", "statistics", 0.85),
            ("Le Monde", "https://www.lemonde.fr", "news", 0.6),
        ],
    ),
    _country(
        "Government of Japan",
        "JP",
        ["japan", "nippon"],
        ["japan.go.jp", "e-gov.go.jp"],
        "Government of Japan.",
        [
            ("Ministry of Finance", "ministry", "https://www.mof.go.jp"),
            ("National Diet — House of Representatives", "parliament", "https://www.shugiin.go.jp"),
            ("Board of Audit of Japan", "audit", "https://www.jbaudit.go.jp"),
            ("Statistics Bureau of Japan", "statistics", "https://www.stat.go.jp"),
            ("Bank of Japan", "central_bank", "https://www.boj.or.jp"),
            ("Digital Agency", "procurement", "https://www.digital.go.jp"),
        ],
        [
            ("Ministry of Finance — budget", "https://www.mof.go.jp", "budget", 0.9),
            ("e-Gov portal", "https://www.e-gov.go.jp", "government", 0.9),
            ("Board of Audit reports", "https://www.jbaudit.go.jp", "audit", 0.9),
            ("Statistics Bureau", "https://www.stat.go.jp", "statistics", 0.9),
            ("House of Representatives", "https://www.shugiin.go.jp", "parliament", 0.9),
            ("GEPS — government e-procurement", "https://www.geps.go.jp", "procurement", 0.85),
            ("data.go.jp — open data", "https://www.data.go.jp", "statistics", 0.85),
            ("NHK News", "https://www3.nhk.or.jp/news/", "news", 0.6),
        ],
    ),
    _country(
        "Government of Canada",
        "CA",
        ["canada"],
        ["canada.ca"],
        "Federal government of Canada.",
        [
            ("Department of Finance Canada", "ministry", "https://www.canada.ca/en/department-finance.html"),
            ("Parliament of Canada", "parliament", "https://www.parl.ca"),
            ("Office of the Auditor General", "audit", "https://www.oag-bvg.gc.ca"),
            ("Statistics Canada", "statistics", "https://www.statcan.gc.ca"),
            ("Bank of Canada", "central_bank", "https://www.bankofcanada.ca"),
            ("Public Services and Procurement Canada", "procurement", "https://www.canada.ca/en/public-services-procurement.html"),
        ],
        [
            ("Budget of Canada", "https://budget.canada.ca", "budget", 0.9),
            ("CanadaBuys — tenders", "https://canadabuys.canada.ca", "procurement", 0.9),
            ("Auditor General reports", "https://www.oag-bvg.gc.ca", "audit", 0.9),
            ("Statistics Canada", "https://www.statcan.gc.ca", "statistics", 0.9),
            ("Parliament of Canada", "https://www.parl.ca", "parliament", 0.9),
            ("Justice Laws Website", "https://laws-lois.justice.gc.ca", "legal", 0.9),
            ("Open Government Portal", "https://open.canada.ca", "statistics", 0.85),
            ("CBC News", "https://www.cbc.ca/news", "news", 0.6),
        ],
    ),
    _country(
        "Australian Government",
        "AU",
        ["australia", "commonwealth of australia", "government of australia"],
        ["australia.gov.au", "gov.au"],
        "Government of the Commonwealth of Australia.",
        [
            ("The Treasury", "ministry", "https://treasury.gov.au"),
            ("Parliament of Australia", "parliament", "https://www.aph.gov.au"),
            ("Australian National Audit Office", "audit", "https://www.anao.gov.au"),
            ("Australian Bureau of Statistics", "statistics", "https://www.abs.gov.au"),
            ("Reserve Bank of Australia", "central_bank", "https://www.rba.gov.au"),
            ("Department of Finance", "procurement", "https://www.finance.gov.au"),
        ],
        [
            ("Budget.gov.au", "https://budget.gov.au", "budget", 0.9),
            ("AusTender", "https://www.tenders.gov.au", "procurement", 0.9),
            ("ANAO audit reports", "https://www.anao.gov.au", "audit", 0.9),
            ("Australian Bureau of Statistics", "https://www.abs.gov.au", "statistics", 0.9),
            ("Parliament of Australia", "https://www.aph.gov.au", "parliament", 0.9),
            ("Federal Register of Legislation", "https://www.legislation.gov.au", "legal", 0.9),
            ("data.gov.au", "https://data.gov.au", "statistics", 0.85),
            ("ABC News", "https://www.abc.net.au/news", "news", 0.6),
        ],
    ),
    _country(
        "Government of South Korea",
        "KR",
        ["south korea", "korea", "republic of korea"],
        ["korea.kr", "go.kr"],
        "Government of the Republic of Korea.",
        [
            ("Ministry of Economy and Finance", "ministry", "https://www.moef.go.kr"),
            ("National Assembly", "parliament", "https://www.assembly.go.kr"),
            ("Board of Audit and Inspection", "audit", "https://www.bai.go.kr"),
            ("Statistics Korea", "statistics", "https://kostat.go.kr"),
            ("Bank of Korea", "central_bank", "https://www.bok.or.kr"),
            ("Public Procurement Service", "procurement", "https://www.pps.go.kr"),
        ],
        [
            ("Open Fiscal Data", "https://www.openfiscaldata.go.kr", "budget", 0.9),
            ("KONEPS — national e-procurement", "https://www.g2b.go.kr", "procurement", 0.9),
            ("Board of Audit and Inspection", "https://www.bai.go.kr", "audit", 0.9),
            ("Statistics Korea", "https://kostat.go.kr", "statistics", 0.9),
            ("National Assembly", "https://www.assembly.go.kr", "parliament", 0.9),
            ("National Law Information Center", "https://www.law.go.kr", "legal", 0.9),
            ("data.go.kr — open data", "https://www.data.go.kr", "statistics", 0.85),
            ("The Korea Herald", "https://www.koreaherald.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Singapore",
        "SG",
        ["singapore", "republic of singapore"],
        ["gov.sg"],
        "Government of the Republic of Singapore.",
        [
            ("Ministry of Finance", "ministry", "https://www.mof.gov.sg"),
            ("Parliament of Singapore", "parliament", "https://www.parliament.gov.sg"),
            ("Auditor-General's Office", "audit", "https://www.ago.gov.sg"),
            ("Department of Statistics", "statistics", "https://www.singstat.gov.sg"),
            ("Monetary Authority of Singapore", "central_bank", "https://www.mas.gov.sg"),
            ("GovTech", "procurement", "https://www.tech.gov.sg"),
        ],
        [
            ("Singapore Budget", "https://www.mof.gov.sg/singaporebudget", "budget", 0.9),
            ("GeBIZ — government procurement", "https://www.gebiz.gov.sg", "procurement", 0.9),
            ("Auditor-General's Office reports", "https://www.ago.gov.sg", "audit", 0.9),
            ("SingStat", "https://www.singstat.gov.sg", "statistics", 0.9),
            ("Parliament of Singapore", "https://www.parliament.gov.sg", "parliament", 0.9),
            ("Singapore Statutes Online", "https://sso.agc.gov.sg", "legal", 0.9),
            ("data.gov.sg", "https://data.gov.sg", "statistics", 0.85),
            ("The Straits Times", "https://www.straitstimes.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Norway",
        "NO",
        ["norway", "norge", "kingdom of norway"],
        ["regjeringen.no"],
        "Government of the Kingdom of Norway.",
        [
            ("Ministry of Finance", "ministry", "https://www.regjeringen.no/en/dep/fin"),
            ("Storting", "parliament", "https://www.stortinget.no"),
            ("Office of the Auditor General", "audit", "https://www.riksrevisjonen.no"),
            ("Statistics Norway", "statistics", "https://www.ssb.no"),
            ("Norges Bank", "central_bank", "https://www.norges-bank.no"),
            ("DFØ — Agency for Public and Financial Management", "procurement", "https://dfo.no"),
        ],
        [
            ("Regjeringen — government portal", "https://www.regjeringen.no", "government", 0.9),
            ("Doffin — procurement notices", "https://www.doffin.no", "procurement", 0.9),
            ("Riksrevisjonen reports", "https://www.riksrevisjonen.no", "audit", 0.9),
            ("Statistics Norway", "https://www.ssb.no", "statistics", 0.9),
            ("Stortinget", "https://www.stortinget.no", "parliament", 0.9),
            ("Lovdata — law", "https://lovdata.no", "legal", 0.9),
            ("data.norge.no — open data", "https://data.norge.no", "statistics", 0.85),
            ("NRK", "https://www.nrk.no", "news", 0.6),
        ],
    ),
    # ---------------------------------------------------- middle-income ----
    _country(
        "Federal Government of Brazil",
        "BR",
        ["brazil", "brasil", "government of brazil", "federative republic of brazil"],
        ["gov.br"],
        "Federal government of the Federative Republic of Brazil.",
        [
            ("Ministério da Fazenda", "ministry", "https://www.gov.br/fazenda"),
            ("Câmara dos Deputados", "parliament", "https://www.camara.leg.br"),
            ("Tribunal de Contas da União", "audit", "https://portal.tcu.gov.br"),
            ("IBGE", "statistics", "https://www.ibge.gov.br"),
            ("Banco Central do Brasil", "central_bank", "https://www.bcb.gov.br"),
            ("Ministério da Gestão e da Inovação", "procurement", "https://www.gov.br/gestao"),
        ],
        [
            ("Portal da Transparência", "https://portaldatransparencia.gov.br", "budget", 0.9),
            ("Compras.gov.br — procurement", "https://www.gov.br/compras", "procurement", 0.9),
            ("TCU — audit court", "https://portal.tcu.gov.br", "audit", 0.9),
            ("IBGE statistics", "https://www.ibge.gov.br", "statistics", 0.9),
            ("Câmara dos Deputados", "https://www.camara.leg.br", "parliament", 0.9),
            ("Planalto — legislation", "https://www.planalto.gov.br", "legal", 0.9),
            ("dados.gov.br — open data", "https://dados.gov.br", "statistics", 0.85),
            ("Folha de S.Paulo", "https://www.folha.uol.com.br", "news", 0.6),
        ],
    ),
    _country(
        "Government of India",
        "IN",
        ["india", "bharat", "republic of india"],
        ["india.gov.in"],
        "Government of the Republic of India.",
        [
            ("Ministry of Finance", "ministry", "https://finmin.nic.in"),
            ("Parliament of India", "parliament", "https://sansad.in"),
            ("Comptroller and Auditor General", "audit", "https://cag.gov.in"),
            ("Ministry of Statistics (MoSPI)", "statistics", "https://www.mospi.gov.in"),
            ("Reserve Bank of India", "central_bank", "https://www.rbi.org.in"),
            ("Government e-Marketplace", "procurement", "https://gem.gov.in"),
        ],
        [
            ("Union Budget portal", "https://www.indiabudget.gov.in", "budget", 0.9),
            ("Central Public Procurement Portal", "https://eprocure.gov.in", "procurement", 0.9),
            ("CAG audit reports", "https://cag.gov.in", "audit", 0.9),
            ("MoSPI statistics", "https://www.mospi.gov.in", "statistics", 0.9),
            ("Parliament of India", "https://sansad.in", "parliament", 0.9),
            ("India Code — legislation", "https://www.indiacode.nic.in", "legal", 0.9),
            ("data.gov.in — open data", "https://data.gov.in", "statistics", 0.85),
            ("The Hindu", "https://www.thehindu.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Indonesia",
        "ID",
        ["indonesia", "republic of indonesia"],
        ["indonesia.go.id"],
        "Government of the Republic of Indonesia.",
        [
            ("Kementerian Keuangan", "ministry", "https://www.kemenkeu.go.id"),
            ("DPR RI — House of Representatives", "parliament", "https://www.dpr.go.id"),
            ("BPK — Supreme Audit Board", "audit", "https://www.bpk.go.id"),
            ("BPS — Statistics Indonesia", "statistics", "https://www.bps.go.id"),
            ("Bank Indonesia", "central_bank", "https://www.bi.go.id"),
            ("LKPP — procurement policy agency", "procurement", "https://www.lkpp.go.id"),
        ],
        [
            ("Kementerian Keuangan — budget", "https://www.kemenkeu.go.id", "budget", 0.9),
            ("INAPROC — national procurement", "https://inaproc.id", "procurement", 0.85),
            ("BPK audit reports", "https://www.bpk.go.id", "audit", 0.9),
            ("BPS statistics", "https://www.bps.go.id", "statistics", 0.9),
            ("DPR RI", "https://www.dpr.go.id", "parliament", 0.9),
            ("Peraturan.go.id — regulations", "https://peraturan.go.id", "legal", 0.85),
            ("data.go.id — open data", "https://data.go.id", "statistics", 0.85),
            ("Kompas", "https://www.kompas.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Mexico",
        "MX",
        ["mexico", "méxico", "united mexican states"],
        ["gob.mx"],
        "Federal government of the United Mexican States.",
        [
            ("Secretaría de Hacienda y Crédito Público", "ministry", "https://www.gob.mx/shcp"),
            ("Cámara de Diputados", "parliament", "https://www.diputados.gob.mx"),
            ("Auditoría Superior de la Federación", "audit", "https://www.asf.gob.mx"),
            ("INEGI", "statistics", "https://www.inegi.org.mx"),
            ("Banco de México", "central_bank", "https://www.banxico.org.mx"),
            ("Secretaría de la Función Pública", "procurement", "https://www.gob.mx/sfp"),
        ],
        [
            ("Transparencia Presupuestaria", "https://www.transparenciapresupuestaria.gob.mx", "budget", 0.9),
            ("ComprasMX — public contracts", "https://comprasmx.buengobierno.gob.mx", "procurement", 0.8),
            ("ASF audit reports", "https://www.asf.gob.mx", "audit", 0.9),
            ("INEGI statistics", "https://www.inegi.org.mx", "statistics", 0.9),
            ("Cámara de Diputados", "https://www.diputados.gob.mx", "parliament", 0.9),
            ("Diario Oficial de la Federación", "https://www.dof.gob.mx", "legal", 0.9),
            ("datos.gob.mx — open data", "https://datos.gob.mx", "statistics", 0.85),
            ("El Universal", "https://www.eluniversal.com.mx", "news", 0.6),
        ],
    ),
    _country(
        "Government of South Africa",
        "ZA",
        ["south africa", "republic of south africa"],
        ["gov.za"],
        "Government of the Republic of South Africa.",
        [
            ("National Treasury", "ministry", "https://www.treasury.gov.za"),
            ("Parliament of South Africa", "parliament", "https://www.parliament.gov.za"),
            ("Auditor-General South Africa", "audit", "https://www.agsa.co.za"),
            ("Statistics South Africa", "statistics", "https://www.statssa.gov.za"),
            ("South African Reserve Bank", "central_bank", "https://www.resbank.co.za"),
            ("Office of the Chief Procurement Officer", "procurement", "https://ocpo.treasury.gov.za"),
        ],
        [
            ("Vulekamali — budget data portal", "https://vulekamali.gov.za", "budget", 0.9),
            ("eTenders portal", "https://www.etenders.gov.za", "procurement", 0.85),
            ("Auditor-General reports", "https://www.agsa.co.za", "audit", 0.9),
            ("Statistics South Africa", "https://www.statssa.gov.za", "statistics", 0.9),
            ("Parliament of South Africa", "https://www.parliament.gov.za", "parliament", 0.9),
            ("South African Government portal", "https://www.gov.za", "government", 0.9),
            ("News24", "https://www.news24.com", "news", 0.6),
        ],
    ),
    # ----------------------------------------------------- lower-income ----
    _country(
        "Federal Government of Nigeria",
        "NG",
        ["nigeria", "government of nigeria", "federal republic of nigeria"],
        ["nigeria.gov.ng"],
        "Federal government of the Federal Republic of Nigeria.",
        [
            ("Federal Ministry of Finance", "ministry", "https://finance.gov.ng"),
            ("National Assembly", "parliament", "https://nass.gov.ng"),
            ("Office of the Auditor-General for the Federation", "audit", "https://oaugf.ng"),
            ("National Bureau of Statistics", "statistics", "https://nigerianstat.gov.ng"),
            ("Central Bank of Nigeria", "central_bank", "https://www.cbn.gov.ng"),
            ("Bureau of Public Procurement", "procurement", "https://www.bpp.gov.ng"),
        ],
        [
            ("Budget Office of the Federation", "https://budgetoffice.gov.ng", "budget", 0.85),
            ("NOCOPO — open contracting portal", "https://nocopo.bpp.gov.ng", "procurement", 0.8),
            ("Auditor-General for the Federation", "https://oaugf.ng", "audit", 0.85),
            ("National Bureau of Statistics", "https://nigerianstat.gov.ng", "statistics", 0.85),
            ("National Assembly", "https://nass.gov.ng", "parliament", 0.85),
            ("Central Bank of Nigeria", "https://www.cbn.gov.ng", "central_bank", 0.9),
            ("Premium Times", "https://www.premiumtimesng.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Kenya",
        "KE",
        ["kenya", "republic of kenya"],
        ["kenya.go.ke", "go.ke"],
        "Government of the Republic of Kenya.",
        [
            ("The National Treasury", "ministry", "https://www.treasury.go.ke"),
            ("Parliament of Kenya", "parliament", "https://www.parliament.go.ke"),
            ("Office of the Auditor-General", "audit", "https://www.oagkenya.go.ke"),
            ("Kenya National Bureau of Statistics", "statistics", "https://www.knbs.or.ke"),
            ("Central Bank of Kenya", "central_bank", "https://www.centralbank.go.ke"),
            ("Public Procurement Regulatory Authority", "procurement", "https://www.ppra.go.ke"),
        ],
        [
            ("The National Treasury — budget", "https://www.treasury.go.ke", "budget", 0.85),
            ("Public Procurement Information Portal", "https://tenders.go.ke", "procurement", 0.8),
            ("Auditor-General reports", "https://www.oagkenya.go.ke", "audit", 0.85),
            ("KNBS statistics", "https://www.knbs.or.ke", "statistics", 0.85),
            ("Parliament of Kenya", "https://www.parliament.go.ke", "parliament", 0.85),
            ("Kenya Law — legislation", "https://kenyalaw.org", "legal", 0.85),
            ("Daily Nation", "https://nation.africa", "news", 0.6),
        ],
    ),
    _country(
        "Government of Pakistan",
        "PK",
        ["pakistan", "islamic republic of pakistan"],
        ["pakistan.gov.pk"],
        "Government of the Islamic Republic of Pakistan.",
        [
            ("Ministry of Finance", "ministry", "https://www.finance.gov.pk"),
            ("National Assembly", "parliament", "https://na.gov.pk"),
            ("Auditor-General of Pakistan", "audit", "https://agp.gov.pk"),
            ("Pakistan Bureau of Statistics", "statistics", "https://www.pbs.gov.pk"),
            ("State Bank of Pakistan", "central_bank", "https://www.sbp.org.pk"),
            ("Public Procurement Regulatory Authority", "procurement", "https://www.ppra.org.pk"),
        ],
        [
            ("Ministry of Finance — budget", "https://www.finance.gov.pk", "budget", 0.85),
            ("PPRA — tender notices", "https://www.ppra.org.pk", "procurement", 0.8),
            ("Auditor-General of Pakistan", "https://agp.gov.pk", "audit", 0.85),
            ("Pakistan Bureau of Statistics", "https://www.pbs.gov.pk", "statistics", 0.85),
            ("National Assembly", "https://na.gov.pk", "parliament", 0.85),
            ("State Bank of Pakistan", "https://www.sbp.org.pk", "central_bank", 0.9),
            ("Dawn", "https://www.dawn.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Ghana",
        "GH",
        ["ghana", "republic of ghana"],
        ["ghana.gov.gh"],
        "Government of the Republic of Ghana.",
        [
            ("Ministry of Finance", "ministry", "https://mofep.gov.gh"),
            ("Parliament of Ghana", "parliament", "https://www.parliament.gh"),
            ("Ghana Audit Service", "audit", "https://audit.gov.gh"),
            ("Ghana Statistical Service", "statistics", "https://statsghana.gov.gh"),
            ("Bank of Ghana", "central_bank", "https://www.bog.gov.gh"),
            ("Public Procurement Authority", "procurement", "https://ppa.gov.gh"),
        ],
        [
            ("Ministry of Finance — budget statements", "https://mofep.gov.gh", "budget", 0.85),
            ("GHANEPS — e-procurement", "https://ghaneps.gov.gh", "procurement", 0.8),
            ("Ghana Audit Service reports", "https://audit.gov.gh", "audit", 0.85),
            ("Ghana Statistical Service", "https://statsghana.gov.gh", "statistics", 0.85),
            ("Parliament of Ghana", "https://www.parliament.gh", "parliament", 0.85),
            ("Bank of Ghana", "https://www.bog.gov.gh", "central_bank", 0.9),
            ("Daily Graphic", "https://www.graphic.com.gh", "news", 0.6),
        ],
    ),
    _country(
        "Government of Ethiopia",
        "ET",
        ["ethiopia", "federal democratic republic of ethiopia"],
        ["ethiopia.gov.et"],
        "Federal government of the Federal Democratic Republic of Ethiopia.",
        [
            ("Ministry of Finance", "ministry", "https://www.mofed.gov.et"),
            ("House of Peoples' Representatives", "parliament", "https://www.hopr.gov.et"),
            ("Office of the Federal Auditor General", "audit", "https://ofag.gov.et"),
            ("Ethiopian Statistical Service", "statistics", "https://www.statsethiopia.gov.et"),
            ("National Bank of Ethiopia", "central_bank", "https://nbe.gov.et"),
            ("Public Procurement and Property Authority", "procurement", "https://ppa.gov.et"),
        ],
        [
            ("Ministry of Finance", "https://www.mofed.gov.et", "budget", 0.8),
            ("Public Procurement and Property Authority", "https://ppa.gov.et", "procurement", 0.75),
            ("Federal Auditor General", "https://ofag.gov.et", "audit", 0.8),
            ("Ethiopian Statistical Service", "https://www.statsethiopia.gov.et", "statistics", 0.8),
            ("House of Peoples' Representatives", "https://www.hopr.gov.et", "parliament", 0.8),
            ("National Bank of Ethiopia", "https://nbe.gov.et", "central_bank", 0.85),
            ("Addis Standard", "https://addisstandard.com", "news", 0.6),
        ],
    ),
    _country(
        "Government of Nepal",
        "NP",
        ["nepal", "federal democratic republic of nepal"],
        ["nepal.gov.np"],
        "Government of the Federal Democratic Republic of Nepal.",
        [
            ("Ministry of Finance", "ministry", "https://mof.gov.np"),
            ("Federal Parliament", "parliament", "https://parliament.gov.np"),
            ("Office of the Auditor General", "audit", "https://oag.gov.np"),
            ("National Statistics Office", "statistics", "https://nsonepal.gov.np"),
            ("Nepal Rastra Bank", "central_bank", "https://www.nrb.org.np"),
            ("Public Procurement Monitoring Office", "procurement", "https://ppmo.gov.np"),
        ],
        [
            ("Ministry of Finance — budget", "https://mof.gov.np", "budget", 0.8),
            ("Bolpatra — national e-procurement", "https://bolpatra.gov.np", "procurement", 0.75),
            ("Auditor General reports", "https://oag.gov.np", "audit", 0.8),
            ("National Statistics Office", "https://nsonepal.gov.np", "statistics", 0.8),
            ("Federal Parliament", "https://parliament.gov.np", "parliament", 0.8),
            ("Nepal Rastra Bank", "https://www.nrb.org.np", "central_bank", 0.85),
            ("The Kathmandu Post", "https://kathmandupost.com", "news", 0.6),
        ],
    ),
]
